.circleci/config.yml
setup.py
tests/factories.py
tox.ini

- Add version to Setuptools script.
- Add Tox environment.
- Add version to CI configuration.
More info: https://docs.python.org/3.8/whatsnew/3.8.html

Add Python 3.8 support

---

.circleci/config.yml

Change the PostgreSQL version used for CI to match the version used by the production server `apps-prod-v2` (12.3 since 2020-06-04).

config: Upgrade PostgreSQL to v12.3

---

.circleci/config.yml

We need to use `pip check` because it returns a non-zero exit status
when there are dependency version conflicts. `pip install` just prints a
warning, which does not cause a CI failure.
See also: https://github.com/pypa/pip/issues/6200

config: Verify Python dependency compatibility in CI

---

.circleci/config.yml

CI workflows will finish faster if we do not attempt to build distributable artifacts when tests fail.

config: Make CI 'dist' job depend on 'test' jobs

---

.github/dependabot.yml

Ref: https://github.com/fyntex/fd-django-accounts/pull/169#pullrequestreview-1078160008
Ref: https://cordada.aha.io/features/TECHINFRA-111
Ref: https://github.com/cordada/infra/issues/40

chore: Remove dependabot `time` and `timezone` params

---

.circleci/config.yml
Makefile
docker-compose.test.yml
setup.py
tox.ini

Python 3.6 support ended on 2021-12-23
In order to keep all dependencies updated is needed to drop support of this version in the repository
Ref: https://cordada.aha.io/features/COMPCLDATA-123

chore: Drop support for Python 3.6

---

.bumpversion.cfg
.circleci/config.yml
.example.env
.github/dependabot.yml
HISTORY.rst
Makefile
README.rst
docker-compose.test.yml
docker-compose.yml
fd_dj_accounts/__init__.py
fd_dj_accounts/management/__init__.py
fd_dj_accounts/management/commands/createsuperuser.py
requirements_release.txt
requirements_test.txt
setup.py
tests/settings.py
tests/test_management.py
tox.ini

- (PR #174, 2022-08-19) chore(management): Improve management command `createsuperuser`
- (PR #176, 2022-08-29) chore: Add Make tasks for installation
- (PR #138, 2022-08-31) build(deps): bump wheel from 0.36.2 to 0.37.1
- (PR #178, 2022-09-05) Add testing with Docker Compose
- (PR #177, 2022-09-05) build(deps): bump tox from 3.24.5 to 3.25.1
- (PR #179, 2022-09-06) chore: Drop support for Python 3.6
- (PR #167, 2022-09-06) chore(deps): bump coverage from 5.4 to 6.4.4
- (PR #180, 2022-09-06) build(deps): bump mypy from 0.910 to 0.971
- (PR #175, 2022-09-08) chore(deps): bump setuptools from 53.0.0 to 65.3.0
- (PR #182, 2022-09-22) build(deps): bump twine from 3.3.0 to 4.0.1
- (PR #181, 2022-09-22) chore(deps): bump psycopg2 from 2.8.6 to 2.9.3
- (PR #183, 2022-09-22) chore(deps): bump tox …

Release v0.2.0

---

requirements_release.txt

The release v5.0.0 of `importlib-metadata` removed compatibility shims for deprecated entry point interfaces, which lead to the incompatibility in python 3.7
Pin `importlib-metadata` dependency to maintain CLI compatibility for python 3.7.
Changelog: https://importlib-metadata.readthedocs.io/en/latest/history.html#v5-0-0

fix(requirements): Pin importlib-metadata dependency for python 3.7

---

.circleci/config.yml
Makefile
docker-compose.test.yml
setup.py
tox.ini

- Add version to Setuptools script.
- Add Tox environment.
- Add version to CI configuration.
- Update Docker Compose configuration.
- Update Make task for running tests: `docker-compose-run-test`.
More info: https://docs.python.org/3.9/whatsnew/3.9.html
Ref: https://cordada.aha.io/features/COMPCLDATA-162

feat: Add Python 3.9 support

---

.bumpversion.cfg
.circleci/config.yml
HISTORY.rst
Makefile
docker-compose.test.yml
fd_dj_accounts/__init__.py
requirements_release.txt
setup.py
tox.ini

- (PR #191, 2022-11-10) fix(requirements): Pin importlib-metadata dependency for python 3.7
- (PR #190, 2022-11-11) feat: Add Python 3.9 support

Release v0.3.0

---

fd_dj_accounts/apps.py
fd_dj_accounts/models.py
tests/test_signals.py

Since in our project the method `django.contrib.auth.apps.AuthConfig.ready` will not be executed (because that app is not in `INSTALLED_APPS`) the function `django.contrib.auth.models.update_last_login` will not be registered to the signal `django.contrib.auth.signals.user_logged_in`.
Ref: https://cordada.aha.io/features/COMPCLDATA-179
Ref: https://github.com/fyntex/fd-secrets-manager/issues/28
Ref: https://github.com/fyntex/fd-django-accounts/issues/5

chore: Update `last_login` field on User model

---

.circleci/config.yml
Makefile
docker-compose.test.yml
setup.py
tox.ini

* Add Python 3.10 to Setuptools script.
* Add Tox environment for Python 3.10.
* Add Python 3.10 to CircleCI configuration.
* Add Python 3.10 .black target-version
* Update `docker-compose.yml` file
More information: https://docs.python.org/3.10/whatsnew/3.10.html
Ref: https://cordada.aha.io/features/COMPCLDATA-163

chore: Add support for Python 3.10

---

.bumpversion.cfg
.circleci/config.yml
HISTORY.rst
Makefile
docker-compose.test.yml
fd_dj_accounts/__init__.py
fd_dj_accounts/apps.py
fd_dj_accounts/models.py
setup.py
tests/test_signals.py
tox.ini

- (PR #197, 2022-12-20) chore: Update `last_login` field on User model
- (PR #199, 2023-01-04) chore: Add support for Python 3.10

Release v0.4.0

---

.bumpversion.cfg
HISTORY.rst
fd_dj_accounts/__init__.py

- (PR #204, 2023-01-26) Add GitHub Dependency Review
- (PR #206, 2023-02-06) chore(deps): bump coverage from 6.4.4 to 7.1.0
- (PR #195, 2023-02-06) chore(deps): bump mypy from 0.971 to 0.991
- (PR #201, 2023-02-06) chore(deps): bump wheel from 0.37.1 to 0.38.4
- (PR #207, 2023-02-06) chore(deps): bump setuptools from 65.3.0 to 67.1.0
- (PR #212, 2023-03-07) Switch CI/CD to GitHub actions
- (PR #215, 2023-03-07) chore(deps): bump mypy from 0.991 to 1.1.1

Release v0.5.0

---

.bumpversion.cfg
HISTORY.rst
fd_dj_accounts/__init__.py

- (PR #218, 2023-03-08) Drop support for Python 3.7
- (PR #209, 2023-03-14) chore(deps): bump coverage from 7.1.0 to 7.2.1
- (PR #219, 2023-03-14) chore(deps): bump setuptools from 67.1.0 to 67.6.0
- (PR #220, 2023-03-14) chore: bump actions/cache from 3.2.5 to 3.3.1

Release v0.6.0

---

fd_dj_accounts/models.py
tests/test_models.py

Add custom method `User.__repr__()` that includes the `User’s` `id` in addition to the username.

Add improved `__repr__()` to `User` model

---

.github/workflows/ci-cd.yaml

The CI workflow requires access to the `CODECOV_TOKEN` GitHub secret.
Bug originally introduced in revision 8b5d1037cd4ad34289458a2fb86d8f961c14901f.

Allow GitHub Actions to pass secrets from CI/CD to CI workflow

---

.bumpversion.cfg
HISTORY.rst
fd_dj_accounts/__init__.py

- (PR #258, 2023-09-07) Add Codecov repository upload token; update Codecov status badge
- (PR #261, 2023-09-27) Add dependency groups to Dependabot configuration
- (PR #264, 2023-09-27) Allow GitHub Actions to pass secrets from CI/CD to CI workflow
- (PR #262, 2023-09-27) chore: Bump the production-dependencies group with 4 updates
- (PR #266, 2023-10-17) Add missing tests for `commands.createsuperuser`
- (PR #263, 2023-10-23) chore(deps): Bump tox from 3.26.0 to 4.11.3
- (PR #253, 2023-10-23) chore(deps): Bump wheel from 0.40.0 to 0.41.2
- (PR #267, 2023-10-23) chore(deps): Bump psycopg2 from 2.9.3 to 2.9.9

Release v0.8.0

---

.bumpversion.cfg
.github/dependabot.yml
.github/workflows/ci-cd.yaml
.github/workflows/ci.yaml
.github/workflows/dependency-review.yaml
.github/workflows/deploy.yaml
.github/workflows/release.yaml
HISTORY.rst
README.rst
fd_dj_accounts/__init__.py
requirements_release.txt
requirements_test.txt
tests/test_management.py

Ref: https://github.com/cordada/fd-django-accounts/pull/268

Deploy release v0.8.0

---

.bumpversion.cfg
HISTORY.rst
src/fd_dj_accounts/__init__.py

- (PR #279, 2024-01-10) chore(deps): Bump mypy from 1.4.1 to 1.8.0
- (PR #281, 2024-01-29) chore: Bump the production-dependencies group with 7 updates
- (PR #284, 2024-02-13) Change Python project structure from Flat layout to Src layout
- (PR #285, 2024-02-13) chore: Bump the production-dependencies group with 3 updates
- (PR #286, 2024-02-14) Add Python project configuration
- (PR #275, 2024-02-15) chore(deps): Bump wheel from 0.41.2 to 0.42.0
- (PR #282, 2024-02-16) chore: Bump coverage from 7.2.7 to 7.4.1
- (PR #287, 2024-02-16) chore: Bump setuptools from 68.0.0 to 69.1.0

Release v0.9.0

---

src/fd_dj_accounts/models.py
src/tests/test_models.py

Django Admin requires the user model to define the following attributes and methods:
- `is_staff`: Already defined.
- `is_active`: Already defined.
- `has_perm()`: Defined now.
- `has_module_perms()`: Defined now.

Add methods required by Django Admin to `.models.User`

---

.bumpversion.cfg
HISTORY.rst
src/fd_dj_accounts/__init__.py

- (PR #299, 2024-11-20) deps: Update PostgreSQL from version ≥12.3 to 15.5
- (PR #300, 2024-11-20) chore(deps): Bump the production-dependencies group with 7 updates
- (PR #303, 2024-11-20) chore(deps): Bump flake8 from 6.0.0 to 7.1.1
- (PR #304, 2024-11-20) chore(deps): Bump tox from 4.11.3 to 4.23.2
- (PR #305, 2024-11-21) deps: Update `Django` from ≥2.1 to ≥4.2
- (PR #306, 2024-11-21) Improve type annotations
- (PR #307, 2024-11-22) Update for Django 4.2. ⚠️ Contains breaking changes.
- (PR #308, 2024-11-22) Add methods required by Django Admin to `.models.User`

Release v0.10.0

---

pyproject.toml
requirements_release.txt

- [Software Repository](https://pypi.org/project/setuptools/71.1.0/)
- [Release notes](https://github.com/pypa/setuptools/releases/tag/v71.1.0)
- [Changelog](https://github.com/pypa/setuptools/blob/v71.1.0/NEWS.rst#v7110)
- [Commits](https://github.com/pypa/setuptools/compare/v69.1.0...v71.1.0)

deps: Update `setuptools` from ≤69.1.0 to 71.1.0

---

Makefile
pyproject.toml
requirements_release.txt
setup.cfg

Setuptools has deprecated `python setup.py sdist` and `python setup.py bdist_wheel` in favor of `python -m build`.
This commit replaces the deprecated commands with the new `python -m build` command in `Makefile`, and moves the tool's configuration from `setup.cfg` to `pyproject.toml`.
See also: [How to modernize a `setup.py` based project?](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/) ([GitHub](https://github.com/pypa/packaging.python.org/blob/afb69f3d/source/guides/modernize-setup-py-project.rst))

Replace `setup.py sdist` and `bdist_wheel` with `build`

---

.bumpversion.cfg
HISTORY.rst
src/fd_dj_accounts/__init__.py

- (PR #311, 2024-11-22) Move Mypy, Flake8, Coverage.py configurations to separate configuration files
- (PR #312, 2024-11-22) deps: Update `setuptools` from ≤69.1.0 to 71.1.0
- (PR #313, 2024-11-22) deps: Update `wheel` from ≤0.42.0 to 0.45.0
- (PR #314, 2024-11-22) deps: Update `pip` from 22.3.1 to 24.2
- (PR #315, 2024-11-22) Replace `setup.py sdist` and `bdist_wheel` with `build`
- (PR #316, 2024-11-22) When running `twine check`, fail on warnings
- (PR #318, 2024-11-25) Update Bumpversion configuration to be compliant with Commitlint
- (PR #317, 2024-11-25) Replace Setuptools Configuration with Python Project Configuration

Release v0.11.0

---

requirements_release.txt

- [Software Repository](https://pypi.org/project/twine/5.1.1/)
- [Release notes](https://github.com/pypa/twine/releases/tag/v5.1.1)
- [Changelog](https://github.com/pypa/twine/blob/v5.1.1/docs/changelog.rst#twine-511-2024-06-26)
- [Commits](https://github.com/pypa/twine/compare/4.0.2...v5.1.1)

deps: Update `twine` from 4.0.2 to 5.1.1

---

.bumpversion.cfg
HISTORY.rst
src/fd_dj_accounts/__init__.py

- (PR #328, 2024-12-03) chore: Bump codecov/codecov-action from 5.0.6 to 5.0.7 in the production-dependencies group
- (PR #327, 2024-12-03) chore(deps): Bump mypy from 1.8.0 to 1.13.0
- (PR #326, 2024-12-09) chore(deps): Bump wheel from 0.45.0 to 0.45.1
- (PR #325, 2024-12-09) chore(deps): Bump psycopg2 from 2.9.9 to 2.9.10
- (PR #329, 2025-01-03) chore: Bump the production-dependencies group with 3 updates
- (PR #331, 2025-01-28) chore(deps): Bump twine from 5.1.1 to 6.0.1
- (PR #336, 2025-02-28) chore: Drop support for Python 3.8
- (PR #337, 2025-02-28) chore: Bump the production-dependencies group across 1 directory with 5 updates
- (PR #338, 2025-02-28) Use most recent patch version of Python in CI/CD configuration
- (PR #335, 2025-02-28) chore(deps): Bump twine from 6.0.1 to 6.1.0

Release v0.13.0

---

.coveragerc.test.ini

- Exclude `typing.TYPE_CHECKING`.

Improve test coverage exclusions

---

.bumpversion.cfg
HISTORY.rst
src/fd_dj_accounts/__init__.py

- (PR #339, 2025-03-24) chore(deps): Bump setuptools from 71.1.0 to 75.8.2
- (PR #340, 2025-03-24) chore(deps): Bump mypy from 1.13.0 to 1.15.0
- (PR #341, 2025-03-24) chore(deps): Bump coverage from 7.4.1 to 7.6.12
- (PR #345, 2025-03-24) Improve test coverage exclusions
- (PR #344, 2025-03-24) Require Python ≥3.9

Release v0.14.0

---

pyproject.toml

- `license` must be a valid SPDX license expression.
- License classifiers are deprecated and have been superseded by license expressions (see https://peps.python.org/pep-0639/).
- Add `license-files` to specify the license file. (Not related to the deprecations.)

Fix Python package license metadata deprecations

---

.bumpversion.cfg
HISTORY.rst
src/fd_dj_accounts/__init__.py

- (PR #354, 2025-05-20) chore(deps): Bump setuptools from 75.8.2 to 78.1.1
- (PR #353, 2025-06-09) chore: Bump the production-dependencies group with 6 updates
- (PR #350, 2025-06-26) chore(deps): Bump flake8 from 7.1.1 to 7.2.0
- (PR #355, 2025-06-26) chore(deps): Bump tox from 4.23.2 to 4.26.0
- (PR #356, 2025-06-26) chore(deps): Bump setuptools from 78.1.1 to 80.9.0
- (PR #359, 2025-07-09) chore(deps): Bump coverage from 7.6.12 to 7.9.1
- (PR #360, 2025-07-25) Remove upper bound on Python version
- (PR #357, 2025-07-25) chore(deps): Bump mypy from 1.15.0 to 1.16.1
- (PR #358, 2025-07-25) chore(deps): Bump flake8 from 7.2.0 to 7.3.0
- (PR #361, 2025-07-25) Fix Python package license metadata deprecations

Release v0.15.0

---

.github/workflows/ci.yaml

Pin `codecov/codecov-action` to commit hash instead of tag to improve supply chain security.
Resolves: https://github.com/cordada/fd-django-accounts/security/code-scanning/7

Pin GitHub Action `codecov/codecov-action` to commit hash
